### ISSUE TITLE
Security update from Laravel 4.2.19?

### ISSUE THREAD

**Issue by sdebacker** [jadz/laravel-framework-4.2.18-php7#3]
Recently there where a new Laravel 4.2 version (4.2.19), that contains some security fixes, will you integrate it in this repo?

**Comment by jadz** [comment]
Can you provide me with a link? I'll take a look.

**Comment by sdebacker** [comment]
https://github.com/laravel/framework/compare/v4.2.18...v4.2.19

**Comment by jadz** [comment]
This is now merged.
