### ISSUE TITLE
What is the diffrence between offical repository and this?

### ISSUE THREAD

**Issue by ghost** [jadz/laravel-framework-4.2.18-php7#5]
Hi ,

I have a project I programmed it two years ago by laravel 4.2

Now , I want to run the project in PHP7 , and it look works fine. (just quick testing).

so , what is the diffrence between offical repository and yours?

And if my project works fine. so I need to change it or not.

What do you advice me ?

**Comment by YOzaz** [comment]
PHP7 has changed the way Exceptions are being handled, therefore all internal Laravel Exceptions will fail.
This repo tries to fix it by amending Exceptions to be PHP7 compatible.

**Comment by ghost** [comment]
Thank you @YOzaz , But now what? copy the vendor folder from your repostory and put it in my project.

what do you advice to make my project works find in PHP7

**Comment by YOzaz** [comment]
https://laracasts.com/discuss/channels/laravel/laravel-42-and-php-7

**Comment by ghost** [comment]
thanks @YOzaz
